const RESOURCE_SUBJECTS = [
  'English Writing',
  'Essay Writing',
  '中文',
  '中文/DSE答題思維',
  '中文寫作',
  '中文閱讀理解',
  '化學',
  '地理',
  '數學',
  '數學 Log',
  '數學 M1',
  '數學 M2',
  '歷史',
  '物理',
  '生物',
  '經濟',
  '英文',
  '英文MC技巧',
];

const RESOURCE_TUTORS = [
  'Rita Tsang',
  'Sally Wong',
  'Ashley Lin',
  'Denise Choi',
  'Sally Li',
  'Winter Lau',
  'YY Lam',
  'Tiffany Ng',
  'Terence Tse',
  'A Lam',
  'Bon Lam',
  'JT',
  'K.C. Daniel',
  'H.H. Oscar',
  'Dick Hui',
  'Dick HuixKi Sir',
  'Lag Chun',
  'Leo Sir',
  'Dick HuixPung Sir',
  'JC',
  'Dom Chan',
  'Roy Sir',
  'Sean To',
  'Sabrina Chan',
  'Ango Chung',
  'Woody Leung',
  'Alex Leung',
  'Calvin Sun',
  'Ling Leung',
  'Speech Jeh',
  'Suki Chui',
].filter((name, index, list) => list.indexOf(name) === index);

const TUTOR_ALPHA_RANGES = [
  { id: 'A-C', label: 'A-C', test: (letter) => letter >= 'A' && letter <= 'C' },
  { id: 'D-F', label: 'D-F', test: (letter) => letter >= 'D' && letter <= 'F' },
  { id: 'G-I', label: 'G-I', test: (letter) => letter >= 'G' && letter <= 'I' },
  { id: 'J-L', label: 'J-L', test: (letter) => letter >= 'J' && letter <= 'L' },
  { id: 'M-O', label: 'M-O', test: (letter) => letter >= 'M' && letter <= 'O' },
  { id: 'P-R', label: 'P-R', test: (letter) => letter >= 'P' && letter <= 'R' },
  { id: 'S-U', label: 'S-U', test: (letter) => letter >= 'S' && letter <= 'U' },
  { id: 'V-Z', label: 'V-Z', test: (letter) => letter >= 'V' && letter <= 'Z' },
];

const RESOURCES = [
  {
    id: 'reg0-bridging',
    title: '中四五 / 中六「星」級銜接課程 (REG0)、常規課程',
    date: '2026-05-26',
    subjects: ['中文', '中文寫作'],
    tutors: ['Rita Tsang'],
  },
  {
    id: 'chinese-reading-dse',
    title: 'DSE 中文閱讀理解精讀班',
    date: '2026-05-20',
    subjects: ['中文', '中文閱讀理解', '中文/DSE答題思維'],
    tutors: ['Sally Wong'],
  },
  {
    id: 'math-m1-star',
    title: '數學 M1 星級衝刺班',
    date: '2026-05-18',
    subjects: ['數學', '數學 M1'],
    tutors: ['Terence Tse'],
  },
  {
    id: 'math-m2-log',
    title: '數學 M2 及 Log 專題',
    date: '2026-05-15',
    subjects: ['數學', '數學 M2', '數學 Log'],
    tutors: ['Leo Sir'],
  },
  {
    id: 'english-mc',
    title: '英文 MC 技巧速成',
    date: '2026-05-12',
    subjects: ['英文', '英文MC技巧'],
    tutors: ['Ashley Lin'],
  },
  {
    id: 'english-writing',
    title: 'English Writing Masterclass',
    date: '2026-05-10',
    subjects: ['英文', 'English Writing', 'Essay Writing'],
    tutors: ['Denise Choi'],
  },
  {
    id: 'chemistry-lab',
    title: '化學實驗與溫習筆記',
    date: '2026-05-08',
    subjects: ['化學'],
    tutors: ['Roy Sir'],
  },
  {
    id: 'physics-mechanics',
    title: '物理力學重點整理',
    date: '2026-05-05',
    subjects: ['物理'],
    tutors: ['Dom Chan'],
  },
  {
    id: 'biology-genetics',
    title: '生物遺傳學專題',
    date: '2026-05-03',
    subjects: ['生物'],
    tutors: ['Sabrina Chan'],
  },
  {
    id: 'economics-micro',
    title: '經濟學微觀分析',
    date: '2026-05-01',
    subjects: ['經濟'],
    tutors: ['Sean To'],
  },
  {
    id: 'history-modern',
    title: '歷史現代史專題',
    date: '2026-04-28',
    subjects: ['歷史'],
    tutors: ['Woody Leung'],
  },
  {
    id: 'geography-climate',
    title: '地理氣候與環境',
    date: '2026-04-25',
    subjects: ['地理'],
    tutors: ['Alex Leung'],
  },
  {
    id: 'chinese-writing-rita',
    title: '中文寫作進階班',
    date: '2026-04-22',
    subjects: ['中文', '中文寫作'],
    tutors: ['Rita Tsang'],
  },
  {
    id: 'speech-public',
    title: '公開演講技巧訓練',
    date: '2026-04-20',
    subjects: ['English Writing'],
    tutors: ['Speech Jeh'],
  },
  {
    id: 'math-core-jc',
    title: '數學核心溫習',
    date: '2026-04-18',
    subjects: ['數學'],
    tutors: ['JC'],
  },
];
